In [16]:
import psycopg2
import pandas.io.sql as psql
import pandas as pd
from matplotlib import pyplot as plt
from __future__ import division #now division always returns a floating point number
import numpy as np
%matplotlib inline

In [62]:
db = psycopg2.connect("dbname='fantasyfootball' host='localhost'")

def get_combined_df(week):
    actual_points = psql.read_sql("""
    select name, team, position, season, week, total_points as points_actual 
    from scoring_leaders_weekly where week = '{0}';""".format(week), con=db)
    predicted_points = psql.read_sql("""
        select name, team, position, season, week, total_points as points_predicted
        from next_week_projections where week = '{0}';""".format(week), con=db)
    combined_df = actual_points.merge(predicted_points, 
                                      on=['name', 'team', 'position', 'season', 'week'], how='left')
    combined_df = combined_df.dropna()
    combined_df['points_diff'] = combined_df.points_actual - combined_df.points_predicted
    combined_df['points_diff_pct'] = (combined_df.points_actual - combined_df.points_predicted) / combined_df.points_predicted
    return combined_df

In [63]:
combined_df = get_combined_df('1')

In [64]:
group = combined_df.groupby('position')
top_list = []
bottom_list = []
for name, data in group:
    top = data.sort('points_diff', ascending=False)
    top_list.append(top.head())
    bottom_list.append(top.tail())

In [65]:
top_df = pd.concat(top_list)
top_df

,name,team,position,season,week,points_actual,points_predicted,points_diff,points_diff_pct
26,Broncos,Broncos,D,2015,1,18,6,12,2.000000
14,Panthers,Panthers,D,2015,1,22,12,10,0.833333
51,Ravens,Ravens,D,2015,1,14,4,10,2.500000
32,Titans,Titans,D,2015,1,17,8,9,1.125000
36,Jets,Jets,D,2015,1,16,8,8,1.000000
25,Brandon McManus,Den,K,2015,1,18,8,10,1.250000
29,Josh Brown,NYG,K,2015,1,17,8,9,1.125000
28,Matt Bryant,Atl,K,2015,1,17,9,8,0.888889
43,Robbie Gould,Chi,K,2015,1,14,7,7,1.000000
48,Zach Hocker,NO,K,2015,1,14,8,6,0.750000
4,Carson Palmer,Ari,QB,2015,1,25,16,9,0.562500
1,Tom Brady,NE,QB,2015,1,27,19,8,0.421053
5,Marcus Mariota,Ten,QB,2015,1,24,16,8,0.500000
9,Alex Smith,KC,QB,2015,1,22,14,8,0.571429
23,Nick Foles,StL,QB,2015,1,18,11,7,0.636364
0,Carlos Hyde,SF,RB,2015,1,29,11,18,1.636364
46,Marcel Reece,Oak,RB,2015,1,14,0,14,inf
17,Bishop Sankey,Ten,RB,2015,1,20,6,14,2.333333
21,Danny Woodhead,SD,RB,2015,1,18,6,12,2.000000
11,Matt Forte,Chi,RB,2015,1,22,10,12,1.200000
7,Austin Seferian-Jenkins,TB,TE,2015,1,23,4,19,4.750000
12,Tyler Eifert,Cin,TE,2015,1,22,5,17,3.400000
13,Travis Kelce,KC,TE,2015,1,22,7,15,2.142857
2,Rob Gronkowski,NE,TE,2015,1,27,13,14,1.076923
49,Darren Fells,Ari,TE,2015,1,14,2,12,6.000000
6,DeAndre Hopkins,Hou,WR,2015,1,23,9,14,1.555556
47,Travis Benjamin,Cle,WR,2015,1,14,2,12,6.000000
30,James Jones,GB,WR,2015,1,17,6,11,1.833333
3,Julio Jones,Atl,WR,2015,1,26,15,11,0.733333
34,Kendall Wright,Ten,WR,2015,1,16,6,10,1.666667

In [66]:
bottom_df = pd.concat(bottom_list)
bottom_df

,name,team,position,season,week,points_actual,points_predicted,points_diff,points_diff_pct
218,Cowboys,Cowboys,D,2015,1,3,5,-2,-0.400000
195,Vikings,Vikings,D,2015,1,4,7,-3,-0.428571
197,Chargers,Chargers,D,2015,1,4,7,-3,-0.428571
261,Texans,Texans,D,2015,1,2,7,-5,-0.714286
299,Browns,Browns,D,2015,1,1,8,-7,-0.875000
180,Stephen Gostkowski,NE,K,2015,1,4,9,-5,-0.555556
255,Jason Myers,Jac,K,2015,1,2,7,-5,-0.714286
260,Kyle Brindza,TB,K,2015,1,2,7,-5,-0.714286
239,Blair Walsh,Min,K,2015,1,2,8,-6,-0.750000
262,Sebastian Janikowski,Oak,K,2015,1,1,8,-7,-0.875000
86,Colin Kaepernick,SF,QB,2015,1,10,17,-7,-0.411765
264,Josh McCown,Cle,QB,2015,1,1,9,-8,-0.888889
132,Eli Manning,NYG,QB,2015,1,7,17,-10,-0.588235
248,Derek Carr,Oak,QB,2015,1,2,13,-11,-0.846154
162,Peyton Manning,Den,QB,2015,1,5,17,-12,-0.705882
199,Frank Gore,Ind,RB,2015,1,3,9,-6,-0.666667
215,Isaiah Crowell,Cle,RB,2015,1,3,9,-6,-0.666667
117,LeSean McCoy,Buf,RB,2015,1,8,15,-7,-0.466667
164,Adrian Peterson,Min,RB,2015,1,5,16,-11,-0.687500
211,C.J. Anderson,Den,RB,2015,1,3,14,-11,-0.785714
249,Crockett Gillmore,Bal,TE,2015,1,2,5,-3,-0.600000
265,Benjamin Watson,NO,TE,2015,1,1,4,-3,-0.750000
268,Jacob Tamme,Atl,TE,2015,1,1,4,-3,-0.750000
242,Larry Donnell,NYG,TE,2015,1,2,6,-4,-0.666667
267,Greg Olsen,Car,TE,2015,1,1,7,-6,-0.857143
273,Torrey Smith,SF,WR,2015,1,1,8,-7,-0.875000
153,Demaryius Thomas,Den,WR,2015,1,6,14,-8,-0.571429
182,Dez Bryant*,Dal,WR,2015,1,4,14,-10,-0.714286
201,Calvin Johnson,Det,WR,2015,1,3,14,-11,-0.785714
189,Odell Beckham Jr.,NYG,WR,2015,1,4,15,-11,-0.733333